/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выход */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий админ */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сменить пароль */
        post: operations["change-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Активные сессии */
        get: operations["list-sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Завершить сессию */
        delete: operations["revoke-session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выключить 2FA */
        post: operations["totp-disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Включить 2FA */
        post: operations["totp-enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/totp/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Начать настройку 2FA */
        post: operations["totp-setup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Подключения */
        get: operations["list-inbounds"];
        put?: never;
        /** Добавить подключение */
        post: operations["create-inbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbounds/check-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить сайт как цель REALITY */
        post: operations["check-target"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbounds/scan-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подобрать цели REALITY рядом с сервером */
        post: operations["scan-targets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbounds/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить шаблон листенера без сохранения */
        post: operations["validate-inbound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbounds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить подключение */
        delete: operations["delete-inbound"];
        options?: never;
        head?: never;
        /** Изменить подключение */
        patch: operations["update-inbound"];
        trace?: never;
    };
    "/api/v1/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Состояние ноды */
        get: operations["node-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ноды */
        get: operations["list-nodes"];
        put?: never;
        /** Добавить ноду */
        post: operations["create-node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить ноду */
        delete: operations["delete-node"];
        options?: never;
        head?: never;
        /** Изменить ноду */
        patch: operations["update-node"];
        trace?: never;
    };
    "/api/v1/nodes/{id}/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выпустить новый ключ ноды (старый перестаёт работать) */
        post: operations["rekey-node"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Доступные пресеты подключений */
        get: operations["list-presets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Настройки */
        get: operations["get-settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить настройки */
        patch: operations["update-settings"];
        trace?: never;
    };
    "/api/v1/settings/certificate/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запросить сертификат Let's Encrypt сейчас */
        post: operations["renew-certificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/reset-admin-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выдать новую секретную ссылку на панель */
        post: operations["reset-admin-path"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Показатели дашборда */
        get: operations["stats-overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Трафик сервера */
        get: operations["stats-traffic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Тарифы */
        get: operations["list-tariffs"];
        put?: never;
        /** Создать тариф */
        post: operations["create-tariff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tariffs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Изменить тариф */
        put: operations["update-tariff"];
        post?: never;
        /** Убрать тариф в архив */
        delete: operations["archive-tariff"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telegram-бот */
        get: operations["get-telegram"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Настроить Telegram-бота */
        patch: operations["update-telegram"];
        trace?: never;
    };
    "/api/v1/telegram/broadcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Разослать сообщение всем в боте */
        post: operations["telegram-broadcast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Обновления */
        get: operations["get-updates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Включить или выключить автообновление */
        patch: operations["update-updates"];
        trace?: never;
    };
    "/api/v1/updates/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить обновления сейчас */
        post: operations["check-updates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/updates/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить сейчас: заявка серверу */
        post: operations["request-update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список пользователей */
        get: operations["list-users"];
        put?: never;
        /** Создать пользователя по тарифу */
        post: operations["create-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Массовое действие */
        post: operations["bulk-users"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Пользователь */
        get: operations["get-user"];
        put?: never;
        post?: never;
        /** Удалить пользователя */
        delete: operations["delete-user"];
        options?: never;
        head?: never;
        /** Изменить пользователя */
        patch: operations["update-user"];
        trace?: never;
    };
    "/api/v1/users/{id}/bound-devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Устройства, привязанные к подписке */
        get: operations["user-bound-devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/bound-devices/{device}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Отвязать устройство: его ключи сгорают */
        delete: operations["unbind-device"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Адреса, с которых заходил пользователь */
        get: operations["user-devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Продлить */
        post: operations["extend-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Перевыпустить ссылку */
        post: operations["reissue-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/reset-traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Сбросить трафик */
        post: operations["reset-user-traffic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Отвязать подписку от Telegram */
        delete: operations["unlink-telegram"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/traffic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** График трафика пользователя */
        get: operations["user-traffic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminView: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            last_login_at?: string;
            totp_enabled: boolean;
            username: string;
        };
        AutoEvent: {
            /** Format: date-time */
            at: string;
            /** @enum {string} */
            kind: "port" | "sni";
            new: string;
            old: string;
            /** @enum {string} */
            reason: "blocked" | "target_down" | "still_blocked";
        };
        AutoView: {
            /**
             * Format: int64
             * @description Сколько таких устройств
             */
            blocked: number;
            /** @description Устройства, которые доходят до других подключений ноды, до этого не доходят */
            cut_off: boolean;
            /** @description Последняя автоматическая смена */
            last?: components["schemas"]["AutoEvent"];
            /**
             * Format: int64
             * @description Сколько из проверяющих все подключения устройств до него дошли
             */
            reached: number;
            /** Format: date-time */
            since?: string;
            /**
             * @description Почему отрезанное подключение остаётся как есть
             * @enum {string}
             */
            stuck?: "off" | "waiting" | "no_port" | "no_target" | "exhausted";
            target_error?: string;
            target_ok?: boolean;
        };
        BoundDeviceView: {
            app: string;
            /** Format: date-time */
            created_at: string;
            /** @description ID устройства от приложения; пусто — общее место приложений без ID */
            hwid: string;
            /** Format: int64 */
            id: number;
            last_ip: string;
            /** Format: date-time */
            last_seen: string;
            model: string;
            online: boolean;
            os: string;
            os_version: string;
        };
        BroadcastInputBody: {
            /** @description Обычный текст; {brand} — название сервиса */
            text: string;
        };
        BroadcastOutputBody: {
            /** Format: int64 */
            queued: number;
        };
        BulkInputBody: {
            /** @enum {string} */
            action: "extend" | "reset" | "disable" | "enable" | "delete";
            /**
             * Format: int64
             * @description Для extend; не задано — на один период: до следующего дня оплаты или на 30 дней
             */
            days?: number;
            ids: number[];
        };
        BulkOutputBody: {
            /** Format: int64 */
            affected: number;
        };
        CheckTargetInputBody: {
            /** @description host:port */
            dest: string;
            /** @description Имя для клиентов; по умолчанию — хост из dest */
            sni?: string;
        };
        Config: {
            /** @description Кнопки главного меню по порядку */
            buttons: components["schemas"]["MenuButton"][];
            /** @description Удалять сообщения пользователя, чтобы в чате было одно меню */
            clean_chat: boolean;
            /**
             * @description Язык встроенных надписей бота
             * @enum {string}
             */
            lang: "ru" | "en";
            /** @description Кнопка Mini App со страницей подписки */
            mini_app: boolean;
            notify: components["schemas"]["Notify"];
            /** @description Уведомления с 22:00 до 9:00 МСК приходят без звука */
            quiet_night: boolean;
            texts: components["schemas"]["Texts"];
        };
        CreateInboundInputBody: {
            /** @description Шаблон листенера (YAML) для preset=custom */
            config?: string;
            /** @description host:port для REALITY */
            dest?: string;
            /**
             * Format: int64
             * @description Нода; по умолчанию — своя нода панели
             */
            node_id?: number;
            port?: string;
            /** @enum {string} */
            preset: "vless_reality_xhttp" | "hysteria2" | "tuic_v5" | "vless_reality_vision" | "vless_reality_grpc" | "trojan_reality" | "anytls" | "vless_reality_xhttp_pq" | "trusttunnel" | "shadowquic" | "mieru" | "shadowsocks_2022" | "sudoku" | "snell" | "custom";
        };
        CreateNodeInputBody: {
            /**
             * Format: int64
             * @description Порт API ноды; по умолчанию случайный
             */
            api_port?: number;
            /** @description Домен для Hysteria2/TUIC и ссылок (необязательно) */
            domain?: string;
            /** @description IP или имя сервера ноды */
            host: string;
            name: string;
        };
        CreateUserInputBody: {
            contact?: string;
            name: string;
            note?: string;
            tags?: string[];
            /** Format: int64 */
            tariff_id: number;
        };
        DeviceView: {
            client: string;
            /** Format: date-time */
            first_seen: string;
            ip: string;
            /** Format: date-time */
            last_seen: string;
            online: boolean;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][];
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ExtendInputBody: {
            /** Format: int64 */
            days?: number;
            /**
             * Format: int64
             * @description Месяцами: до дня оплаты или того же числа
             */
            months?: number;
        };
        HostStatus: {
            /** @description RFC 3339 */
            at: string;
            error: string;
            from: string;
            /** @enum {string} */
            state: "running" | "ok" | "failed";
            version: string;
        };
        InboundView: {
            /** @description Приложения, которым подключение попадает в подписку: mihomo, xray, singbox, stash, other */
            apps: string[];
            auto: components["schemas"]["AutoView"];
            /** @description Панель сама переносит подключение на другой порт, если его блокируют (и включено в настройках) */
            auto_port: boolean;
            /** @description Панель сама меняет сайт маскировки REALITY, если он перестал подходить (и включено в настройках) */
            auto_sni: boolean;
            /** @description Шаблон листенера (YAML) */
            config: string;
            /** @description Сайт для маскировки REALITY */
            dest?: string;
            /** @description Своё имя в подписке; пусто — имя по умолчанию */
            display_name: string;
            enabled: boolean;
            error?: string;
            /** Format: int64 */
            id: number;
            name: string;
            network: string;
            /** Format: int64 */
            node_id: number;
            port: string;
            preset: string;
            server_names?: string[];
            /** @description Один ключ на всех: учёт, лимиты и отключение по пользователям не работают */
            shared?: boolean;
            /** @enum {string} */
            status: "ok" | "error" | "unknown";
            /** @description Имя, которое увидит клиент */
            sub_name: string;
            title: string;
            /** @description Тип листенера mihomo */
            type: string;
            /** Format: date-time */
            updated_at: string;
        };
        Info: {
            apps?: string;
            default: boolean;
            default_name: string;
            default_port: string;
            id: string;
            network: string;
            shared?: boolean;
            sub_name: string;
            summary: string;
            title: string;
            type: string;
        };
        ListUsersOutputBody: {
            counts: components["schemas"]["UserCounts"];
            items: components["schemas"]["UserView"][];
            /**
             * Format: int64
             * @description Сколько подходит под фильтр
             */
            total: number;
        };
        ListenerStatus: {
            error?: string;
            name: string;
            ok: boolean;
        };
        LoginInputBody: {
            password: string;
            /** @description Код из приложения или резервный код */
            totp?: string;
            username: string;
        };
        MeBody: {
            admin: components["schemas"]["AdminView"];
            csrf_token: string;
        };
        MenuButton: {
            /** @enum {string} */
            action: "sub" | "devices" | "connect" | "renew" | "support" | "app" | "url" | "page";
            /** @description Постоянный id кнопки */
            id: string;
            label: string;
            on: boolean;
            /** @description В одном ряду с предыдущей */
            row: boolean;
            /** @description Для action=page: текст страницы */
            text?: string;
            /** @description Для action=url: https:// или tg:// */
            url?: string;
        };
        NodeInfo: {
            /** @description host:port API ноды; пусто у своей ноды */
            address: string;
            /** Format: date-time */
            checked_at?: string;
            /** Format: int64 */
            conns: number;
            /** Format: double */
            cpu_percent: number;
            domain: string;
            enabled: boolean;
            error?: string;
            /** @description Адрес для клиентов */
            host: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            inbounds: number;
            /** Format: int64 */
            listeners: number;
            /** Format: int64 */
            listeners_ok: number;
            /** @description Своя нода панели */
            local: boolean;
            /** Format: int64 */
            mem_total: number;
            /** Format: int64 */
            mem_used: number;
            /** @description Группа в подписке, например «🇳🇱 Нидерланды»; её флаг — префикс имён подключений */
            name: string;
            /** @enum {string} */
            status: "ok" | "error" | "unknown";
            version?: string;
        };
        NodeKeyOutputBody: {
            /** @description Команда установки на сервере ноды */
            command: string;
            /** @description Ключ подключения ноды: показывается один раз */
            key: string;
            node: components["schemas"]["NodeInfo"];
        };
        NodeView: {
            /** Format: date-time */
            checked_at: string;
            /** Format: int64 */
            conns: number;
            core: string;
            error?: string;
            listeners: components["schemas"]["ListenerStatus"][];
            ok: boolean;
            /** Format: date-time */
            started_at?: string;
            system: components["schemas"]["System"];
            version: string;
        };
        Notify: {
            expire_1d: boolean;
            expire_3d: boolean;
            expired: boolean;
            traffic_100: boolean;
            traffic_90: boolean;
        };
        OverviewOutputBody: {
            /** Format: int64 */
            expiring_7d: number;
            /** Format: date-time */
            generated_at: string;
            /** Format: int64 */
            online: number;
            /** Format: int64 */
            slots_assigned: number;
            /** Format: int64 */
            slots_free: number;
            top_month: components["schemas"]["TopUser"][];
            /** Format: int64 */
            traffic_today: number;
            /** Format: int64 */
            traffic_yesterday: number;
            /** Format: int64 */
            users_active: number;
            /** Format: int64 */
            users_total: number;
        };
        PasswordInputBody: {
            current: string;
            /** @description Не короче 12 символов */
            new: string;
        };
        PatchInboundInputBody: {
            auto_port?: boolean;
            auto_sni?: boolean;
            /** @description Шаблон листенера (YAML) */
            config?: string;
            dest?: string;
            /** @description Можно с эмодзи: «🇳🇱 Нидерланды». Пусто — имя по умолчанию */
            display_name?: string;
            enabled?: boolean;
            port?: string;
            /** @description SNI для клиентов, если dest — IP (цель из подбора соседей) */
            server_name?: string;
        };
        PatchNodeInputBody: {
            domain?: string;
            enabled?: boolean;
            host?: string;
            name?: string;
        };
        PatchSettingsInputBody: {
            auto_port?: boolean;
            auto_sni?: boolean;
            brand?: string;
            /** @enum {string} */
            default_lang?: "auto" | "ru" | "en";
            device_binding?: boolean;
            device_require_hwid?: boolean;
            domain?: string;
            public_host?: string;
            /** Format: int64 */
            quiet_hour_utc?: number;
            sub_group_auto?: string;
            sub_group_main?: string;
            /** @enum {string} */
            sub_routing?: "ru_direct" | "all";
            /** @description https://… или tg://… */
            support_url?: string;
        };
        PatchTelegramInputBody: {
            config?: components["schemas"]["Config"];
            enabled?: boolean;
            /** @description Токен от @BotFather; пустая строка — удалить */
            token?: string;
        };
        PatchUpdatesInputBody: {
            auto?: boolean;
        };
        PatchUserInputBody: {
            /**
             * Format: int64
             * @description День оплаты 1–31; 0 — убрать
             */
            billing_day?: number;
            contact?: string;
            /** Format: int64 */
            device_limit?: number;
            devices_unlimited?: boolean;
            disabled?: boolean;
            /** Format: date-time */
            expires_at?: string;
            inbounds?: number[];
            name?: string;
            never_expires?: boolean;
            note?: string;
            tags?: string[];
            /**
             * Format: int64
             * @description Применить тариф: лимиты из тарифа, срок — от сегодня
             */
            tariff_id?: number;
            /** Format: int64 */
            traffic_limit?: number;
            traffic_unlimited?: boolean;
        };
        RecoveryOutputBody: {
            /** @description Показываются один раз */
            recovery_codes: string[];
        };
        ResetPathOutputBody: {
            admin_url: string;
        };
        Result: {
            cert_valid: boolean;
            /** @description host:port, который будет набирать нода */
            dest: string;
            /** @description Имя резолвится в этот IP: сайт настоящий, а не чужая маскировка */
            dns_match: boolean;
            error?: string;
            h2: boolean;
            ip: string;
            issuer?: string;
            /** @description Подходит как цель REALITY */
            ok: boolean;
            /** Format: int64 */
            rtt_ms: number;
            /** @description Имя сервера, которое отправят клиенты */
            sni: string;
            tls13: boolean;
            x25519: boolean;
        };
        ScanTargetsOutputBody: {
            /** @description Адрес сервера, вокруг которого искали */
            ip: string;
            results: components["schemas"]["Result"][];
            /** Format: int64 */
            scanned: number;
            /** @description Свой домен с сертификатом панели */
            self_steal?: components["schemas"]["Result"];
        };
        SessionView: {
            /** Format: date-time */
            created_at: string;
            current: boolean;
            id: string;
            ip: string;
            /** Format: date-time */
            last_seen_at: string;
            user_agent: string;
        };
        SettingsView: {
            admin_url: string;
            /** @description Переносить подключение на другой порт, если клиенты перестали до него доходить */
            auto_port: boolean;
            /** @description Менять сайт маскировки REALITY, если он перестал подходить */
            auto_sni: boolean;
            brand: string;
            certificate: components["schemas"]["Status"];
            /**
             * @description Язык админки и страницы подписки, пока человек не выбрал свой; auto — по языку браузера. На нём же названия по умолчанию: группа автовыбора и меню ненастроенного бота
             * @enum {string}
             */
            default_lang: "auto" | "ru" | "en";
            /** @description Привязывать подписку к устройствам: у каждого устройства свои ключи */
            device_binding: boolean;
            /** @description Не выдавать подписку приложениям без ID устройства (иначе они вместе занимают одно место) */
            device_require_hwid: boolean;
            domain: string;
            /** Format: int64 */
            panel_port: number;
            public_host: string;
            /**
             * Format: int64
             * @description Час (UTC), когда пополняется пул слотов: переподключение QUIC-клиентов
             */
            quiet_hour_utc: number;
            sub_base_url: string;
            /** @description Группа автовыбора самого быстрого подключения */
            sub_group_auto: string;
            /** @description Главная группа в Clash-приложениях */
            sub_group_main: string;
            /**
             * @description Маршруты в Clash-приложениях: ru_direct — российские сайты и IP напрямую по геобазам mihomo, all — всё через VPN
             * @enum {string}
             */
            sub_routing: "ru_direct" | "all";
            support_url: string;
        };
        Status: {
            /** Format: date-time */
            checked_at: string;
            error?: string;
            identifier: string;
            /** @enum {string} */
            kind: "self-signed" | "letsencrypt";
            /** Format: date-time */
            not_after: string;
        };
        System: {
            /** Format: double */
            cpu_percent: number;
            /** Format: int64 */
            mem_total: number;
            /** Format: int64 */
            mem_used: number;
            /** Format: int64 */
            net_rx_bps: number;
            /** Format: int64 */
            net_tx_bps: number;
            /** Format: int64 */
            proc_rss: number;
        };
        TariffBody: {
            /**
             * Format: int64
             * @description Срок до этого числа месяца: месяц = от дня оплаты до дня оплаты
             */
            billing_day?: number;
            /** Format: int64 */
            device_limit?: number;
            /** Format: int64 */
            duration_days: number;
            name: string;
            price_label?: string;
            /**
             * @default none
             * @enum {string}
             */
            reset_strategy: "none" | "month_start" | "period";
            /** Format: int64 */
            sort?: number;
            /** Format: int64 */
            traffic_limit?: number;
        };
        TariffView: {
            /**
             * Format: int64
             * @description День месяца, в который заканчивается срок; null — срок в днях
             */
            billing_day: number | null;
            /** Format: int64 */
            device_limit: number | null;
            /**
             * Format: int64
             * @description 0 — бессрочно
             */
            duration_days: number;
            /** Format: int64 */
            id: number;
            name: string;
            price_label: string;
            /** @enum {string} */
            reset_strategy: "none" | "month_start" | "period";
            /** Format: int64 */
            sort: number;
            /**
             * Format: int64
             * @description Байты; null — без лимита
             */
            traffic_limit: number | null;
        };
        TelegramBot: {
            name: string;
            username: string;
        };
        TelegramBroadcast: {
            /** @description Ещё отправляется */
            active: boolean;
            /**
             * Format: int64
             * @description Не дошло: бот заблокирован, чат удалён
             */
            failed: number;
            /** Format: int64 */
            sent: number;
            /**
             * Format: int64
             * @description Unix-время начала
             */
            started: number;
            /** Format: int64 */
            total: number;
        };
        TelegramLink: {
            /** Format: int64 */
            id: number;
            name: string;
            username: string;
        };
        TelegramView: {
            /**
             * Format: int64
             * @description Аккаунтов Telegram с подписками
             */
            accounts: number;
            bot?: components["schemas"]["TelegramBot"];
            /** @description Последняя рассылка с запуска панели */
            broadcast?: components["schemas"]["TelegramBroadcast"];
            config: components["schemas"]["Config"];
            /** @description Встроенные тексты на языке бота: пустое поле берёт их */
            defaults: components["schemas"]["Texts"];
            enabled: boolean;
            /** @description token_invalid, token_revoked, unreachable или ответ Telegram */
            error?: string;
            /**
             * Format: int64
             * @description Подписок, привязанных к Telegram
             */
            linked: number;
            /** @description Адрес Mini App; пусто — Telegram его не откроет: нет адреса или сертификат самоподписанный */
            mini_app_url: string;
            running: boolean;
            /** @description ID бота из токена */
            token_hint?: string;
            /** @description Токен сохранён */
            token_set: boolean;
        };
        Texts: {
            /** @description Уведомление: подписка закончилась */
            expired: string;
            /** @description Уведомление: подписка скоро закончится */
            expiring: string;
            /** @description Шапка главного меню */
            main: string;
            /** @description Экран «Продлить» */
            renew: string;
            /** @description Уведомление: израсходовано 90% трафика */
            traffic_90: string;
            /** @description Уведомление: трафик закончился */
            traffic_end: string;
            /** @description Для тех, у кого ещё нет подписки в боте */
            welcome: string;
        };
        TopUser: {
            /** Format: int64 */
            bytes: number;
            /** Format: int64 */
            id: number;
            name: string;
        };
        TotpCodeInputBody: {
            code: string;
        };
        TotpDisableInputBody: {
            code: string;
            password: string;
        };
        TotpSetupOutputBody: {
            secret: string;
            uri: string;
        };
        TrafficOutputBody: {
            points: components["schemas"]["TrafficPoint"][];
        };
        TrafficPoint: {
            /** Format: int64 */
            down: number;
            /** Format: date-time */
            t: string;
            /** Format: int64 */
            up: number;
        };
        UpdatesView: {
            /** @description Сервер сам ставит новые релизы раз в сутки, ночью */
            auto: boolean;
            /** @description Вышла версия новее этой */
            available: boolean;
            /**
             * Format: int64
             * @description Unix-время последней проверки; 0 — ещё не проверяли
             */
            checked_at: number;
            current: string;
            /** @description Почему последняя проверка не удалась; no_release — релизов ещё нет */
            error: string;
            /** @description Как прошло последнее обновление на сервере */
            host?: components["schemas"]["HostStatus"];
            /** @description Последний релиз; пусто, пока проверки не было */
            latest: string;
            /** @description Что изменилось: markdown по языкам, en и ru */
            notes: {
                [key: string]: string;
            };
            /** @description Когда вышел последний релиз, RFC 3339 */
            published: string;
            /**
             * Format: int64
             * @description Когда нажали «Обновить»; 0 — заявки нет или сервер её уже взял
             */
            requested_at: number;
        };
        UserCounts: {
            /** Format: int64 */
            active: number;
            /** Format: int64 */
            all: number;
            /** Format: int64 */
            disabled: number;
            /** Format: int64 */
            expired: number;
            /** Format: int64 */
            expiring: number;
            /** Format: int64 */
            limited: number;
        };
        UserView: {
            /**
             * Format: int64
             * @description День месяца, в который заканчивается срок (1–31); null — продление днями
             */
            billing_day: number | null;
            contact: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            device_limit: number | null;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: int64 */
            id: number;
            /** @description Разрешённые подключения; пусто — все */
            inbounds: number[];
            name: string;
            note: string;
            online: boolean;
            /** Format: date-time */
            online_at: string | null;
            online_ips: string[];
            /**
             * @description month_start — раз в месяц: в день оплаты, без него 1-го числа
             * @enum {string}
             */
            reset_strategy: "none" | "month_start" | "period";
            /** Format: date-time */
            resets_at: string | null;
            /** @enum {string} */
            state: "active" | "expiring" | "limited" | "expired" | "disabled";
            sub_url: string;
            tags: string[];
            /** Format: int64 */
            tariff_id: number | null;
            /** @description Только в карточке пользователя */
            telegram?: components["schemas"]["TelegramLink"];
            /** Format: int64 */
            total_down: number;
            /** Format: int64 */
            total_up: number;
            /**
             * Format: int64
             * @description Байты за период; null — без лимита
             */
            traffic_limit: number | null;
            /** Format: int64 */
            used_down: number;
            /** Format: int64 */
            used_up: number;
        };
        ValidateInboundInputBody: {
            config: string;
            /** Format: int64 */
            node_id?: number;
            port?: string;
        };
        ValidateInboundOutputBody: {
            network: string;
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "revoke-session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "totp-disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpDisableInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "totp-enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpCodeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "totp-setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetupOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-inbounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboundView"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-inbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInboundInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboundView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "check-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckTargetInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Result"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "scan-targets": {
        parameters: {
            query?: {
                /** @description Нода, рядом с которой искать */
                node_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanTargetsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "validate-inbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateInboundInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateInboundOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-inbound": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-inbound": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchInboundInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboundView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "node-health": {
        parameters: {
            query?: {
                /** @description Нода; 1 — своя нода панели */
                id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeInfo"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNodeInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeKeyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-node": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-node": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchNodeInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeInfo"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "rekey-node": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeKeyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Info"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSettingsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "renew-certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reset-admin-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPathOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "stats-overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "stats-traffic": {
        parameters: {
            query?: {
                range?: "24h" | "7d" | "30d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-tariffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffView"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-tariff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TariffBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-tariff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TariffBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TariffView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "archive-tariff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchTelegramInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "telegram-broadcast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BroadcastInputBody"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BroadcastOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatesView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUpdatesInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatesView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "check-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatesView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "request-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatesView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-users": {
        parameters: {
            query?: {
                state?: "all" | "active" | "expiring" | "limited" | "expired" | "disabled";
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "bulk-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "user-bound-devices": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundDeviceView"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "unbind-device": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                device: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "user-devices": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceView"][];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "extend-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtendInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reissue-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "reset-user-traffic": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "unlink-telegram": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "user-traffic": {
        parameters: {
            query?: {
                range?: "24h" | "7d" | "30d";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrafficOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
