// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legacy.sql

package db

import (
	"context"
)

const addLegacySubToken = `-- name: AddLegacySubToken :exec
INSERT INTO legacy_sub_tokens (token, user_id, source) VALUES ($1, $2, $3)
ON CONFLICT (token) DO NOTHING
`

type AddLegacySubTokenParams struct {
	Token  string
	UserID int64
	Source string
}

func (q *Queries) AddLegacySubToken(ctx context.Context, arg AddLegacySubTokenParams) error {
	_, err := q.db.ExecContext(ctx, addLegacySubToken, arg.Token, arg.UserID, arg.Source)
	return err
}

const countLegacySubTokens = `-- name: CountLegacySubTokens :one
SELECT count(*) FROM legacy_sub_tokens
`

func (q *Queries) CountLegacySubTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLegacySubTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const legacySubTokenUser = `-- name: LegacySubTokenUser :one
SELECT u.id, u.name, u.contact, u.note, u.tags, u.status, u.tariff_id, u.traffic_limit, u.device_limit, u.reset_strategy, u.period_days, u.period_start, u.used_up, u.used_down, u.total_up, u.total_down, u.expires_at, u.inbounds, u.sub_token, u.slot_id, u.online_at, u.created_at, u.updated_at, u.billing_day, u.unbound_at FROM legacy_sub_tokens t JOIN users u ON u.id = t.user_id WHERE t.token = $1
`

func (q *Queries) LegacySubTokenUser(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, legacySubTokenUser, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Note,
		&i.Tags,
		&i.Status,
		&i.TariffID,
		&i.TrafficLimit,
		&i.DeviceLimit,
		&i.ResetStrategy,
		&i.PeriodDays,
		&i.PeriodStart,
		&i.UsedUp,
		&i.UsedDown,
		&i.TotalUp,
		&i.TotalDown,
		&i.ExpiresAt,
		&i.Inbounds,
		&i.SubToken,
		&i.SlotID,
		&i.OnlineAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillingDay,
		&i.UnboundAt,
	)
	return i, err
}

const setImportedUsage = `-- name: SetImportedUsage :exec
UPDATE users SET used_down = $2, total_down = $3, updated_at = $4 WHERE id = $1
`

type SetImportedUsageParams struct {
	ID        int64
	UsedDown  int64
	TotalDown int64
	UpdatedAt int64
}

func (q *Queries) SetImportedUsage(ctx context.Context, arg SetImportedUsageParams) error {
	_, err := q.db.ExecContext(ctx, setImportedUsage,
		arg.ID,
		arg.UsedDown,
		arg.TotalDown,
		arg.UpdatedAt,
	)
	return err
}

const userNameTaken = `-- name: UserNameTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE name = $1)
`

func (q *Queries) UserNameTaken(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userNameTaken, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
