// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Admin struct {
	ID            int64
	Username      string
	PasswordHash  string
	TotpSecret    sql.NullString
	RecoveryCodes sql.NullString
	CreatedAt     int64
	LastLoginAt   sql.NullInt64
}

type AuditLog struct {
	ID         int64
	Ts         int64
	AdminID    sql.NullInt64
	Action     string
	TargetType sql.NullString
	TargetID   sql.NullString
	Ip         sql.NullString
	Details    sql.NullString
}

type Device struct {
	UserID    int64
	Ip        string
	FirstSeen int64
	LastSeen  int64
	Client    string
}

type Inbound struct {
	ID        int64
	Name      string
	Preset    string
	Port      string
	Enabled   int64
	Settings  string
	CreatedAt int64
	UpdatedAt int64
}

type NodeState struct {
	Key   string
	Value string
}

type Session struct {
	IDHash     string
	AdminID    int64
	CsrfToken  string
	CreatedAt  int64
	LastSeenAt int64
	ExpiresAt  int64
	Ip         string
	UserAgent  string
}

type Setting struct {
	Key   string
	Value string
}

type Slot struct {
	ID        int64
	Name      string
	Uuid      string
	Secret    string
	State     string
	CreatedAt int64
	BurnedAt  sql.NullInt64
}

type Tariff struct {
	ID            int64
	Name          string
	TrafficLimit  sql.NullInt64
	DurationDays  int64
	DeviceLimit   sql.NullInt64
	ResetStrategy string
	PriceLabel    string
	Sort          int64
	Archived      int64
	CreatedAt     int64
}

type TrafficDaily struct {
	UserID int64
	Day    int64
	Up     int64
	Down   int64
}

type TrafficHourly struct {
	UserID int64
	Hour   int64
	Up     int64
	Down   int64
}

type User struct {
	ID            int64
	Name          string
	Contact       string
	Note          string
	Tags          string
	Status        string
	TariffID      sql.NullInt64
	TrafficLimit  sql.NullInt64
	DeviceLimit   sql.NullInt64
	ResetStrategy string
	PeriodDays    int64
	PeriodStart   int64
	UsedUp        int64
	UsedDown      int64
	TotalUp       int64
	TotalDown     int64
	ExpiresAt     sql.NullInt64
	Inbounds      sql.NullString
	SubToken      string
	SlotID        sql.NullInt64
	OnlineAt      sql.NullInt64
	CreatedAt     int64
	UpdatedAt     int64
}
