// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (provider, payload, tg_id, kind, user_id, tariff_id, tariff_name, amount, currency, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?)
RETURNING id, provider, payload, external_id, tg_id, kind, user_id, tariff_id, package_id, tariff_name, amount, currency, status, error, pay_url, created_at, paid_at, applied_at, refunded_at
`

type CreatePaymentParams struct {
	Provider   string
	Payload    string
	TgID       int64
	Kind       string
	UserID     sql.NullInt64
	TariffID   sql.NullInt64
	TariffName string
	Amount     int64
	Currency   string
	CreatedAt  int64
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.Provider,
		arg.Payload,
		arg.TgID,
		arg.Kind,
		arg.UserID,
		arg.TariffID,
		arg.TariffName,
		arg.Amount,
		arg.Currency,
		arg.CreatedAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Payload,
		&i.ExternalID,
		&i.TgID,
		&i.Kind,
		&i.UserID,
		&i.TariffID,
		&i.PackageID,
		&i.TariffName,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Error,
		&i.PayUrl,
		&i.CreatedAt,
		&i.PaidAt,
		&i.AppliedAt,
		&i.RefundedAt,
	)
	return i, err
}

const expirePayments = `-- name: ExpirePayments :execrows
UPDATE payments SET status = 'expired' WHERE status = 'pending' AND created_at < ?
`

func (q *Queries) ExpirePayments(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, expirePayments, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findOpenPayment = `-- name: FindOpenPayment :one
SELECT id, provider, payload, external_id, tg_id, kind, user_id, tariff_id, package_id, tariff_name, amount, currency, status, error, pay_url, created_at, paid_at, applied_at, refunded_at FROM payments
WHERE tg_id = ? AND tariff_id = ? AND provider = ? AND kind = ? AND IFNULL(user_id, 0) = ?5
  AND status = 'pending' AND pay_url <> '' AND created_at > ?6
ORDER BY id DESC LIMIT 1
`

type FindOpenPaymentParams struct {
	TgID     int64
	TariffID sql.NullInt64
	Provider string
	Kind     string
	UserID   sql.NullInt64
	Since    int64
}

func (q *Queries) FindOpenPayment(ctx context.Context, arg FindOpenPaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, findOpenPayment,
		arg.TgID,
		arg.TariffID,
		arg.Provider,
		arg.Kind,
		arg.UserID,
		arg.Since,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Payload,
		&i.ExternalID,
		&i.TgID,
		&i.Kind,
		&i.UserID,
		&i.TariffID,
		&i.PackageID,
		&i.TariffName,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Error,
		&i.PayUrl,
		&i.CreatedAt,
		&i.PaidAt,
		&i.AppliedAt,
		&i.RefundedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, provider, payload, external_id, tg_id, kind, user_id, tariff_id, package_id, tariff_name, amount, currency, status, error, pay_url, created_at, paid_at, applied_at, refunded_at FROM payments WHERE id = ?
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Payload,
		&i.ExternalID,
		&i.TgID,
		&i.Kind,
		&i.UserID,
		&i.TariffID,
		&i.PackageID,
		&i.TariffName,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Error,
		&i.PayUrl,
		&i.CreatedAt,
		&i.PaidAt,
		&i.AppliedAt,
		&i.RefundedAt,
	)
	return i, err
}

const getPaymentByExternal = `-- name: GetPaymentByExternal :one
SELECT id, provider, payload, external_id, tg_id, kind, user_id, tariff_id, package_id, tariff_name, amount, currency, status, error, pay_url, created_at, paid_at, applied_at, refunded_at FROM payments WHERE provider = ? AND external_id = ?
`

type GetPaymentByExternalParams struct {
	Provider   string
	ExternalID sql.NullString
}

func (q *Queries) GetPaymentByExternal(ctx context.Context, arg GetPaymentByExternalParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByExternal, arg.Provider, arg.ExternalID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Payload,
		&i.ExternalID,
		&i.TgID,
		&i.Kind,
		&i.UserID,
		&i.TariffID,
		&i.PackageID,
		&i.TariffName,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Error,
		&i.PayUrl,
		&i.CreatedAt,
		&i.PaidAt,
		&i.AppliedAt,
		&i.RefundedAt,
	)
	return i, err
}

const getPaymentByPayload = `-- name: GetPaymentByPayload :one
SELECT id, provider, payload, external_id, tg_id, kind, user_id, tariff_id, package_id, tariff_name, amount, currency, status, error, pay_url, created_at, paid_at, applied_at, refunded_at FROM payments WHERE payload = ?
`

func (q *Queries) GetPaymentByPayload(ctx context.Context, payload string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByPayload, payload)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Payload,
		&i.ExternalID,
		&i.TgID,
		&i.Kind,
		&i.UserID,
		&i.TariffID,
		&i.PackageID,
		&i.TariffName,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Error,
		&i.PayUrl,
		&i.CreatedAt,
		&i.PaidAt,
		&i.AppliedAt,
		&i.RefundedAt,
	)
	return i, err
}

const listOpenPayments = `-- name: ListOpenPayments :many
SELECT id, provider, payload, external_id, tg_id, kind, user_id, tariff_id, package_id, tariff_name, amount, currency, status, error, pay_url, created_at, paid_at, applied_at, refunded_at FROM payments WHERE status IN ('pending', 'paid') AND created_at > ? ORDER BY id
`

func (q *Queries) ListOpenPayments(ctx context.Context, createdAt int64) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listOpenPayments, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Payload,
			&i.ExternalID,
			&i.TgID,
			&i.Kind,
			&i.UserID,
			&i.TariffID,
			&i.PackageID,
			&i.TariffName,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Error,
			&i.PayUrl,
			&i.CreatedAt,
			&i.PaidAt,
			&i.AppliedAt,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, provider, payload, external_id, tg_id, kind, user_id, tariff_id, package_id, tariff_name, amount, currency, status, error, pay_url, created_at, paid_at, applied_at, refunded_at FROM payments
WHERE id < ?1
  AND (?2 = '' OR status = ?2)
  AND (?3 = '' OR provider = ?3)
  AND (?4 = 0 OR user_id = ?4)
ORDER BY id DESC LIMIT ?5
`

type ListPaymentsParams struct {
	BeforeID int64
	Status   interface{}
	Provider interface{}
	UserID   interface{}
	Lim      int64
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments,
		arg.BeforeID,
		arg.Status,
		arg.Provider,
		arg.UserID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Payload,
			&i.ExternalID,
			&i.TgID,
			&i.Kind,
			&i.UserID,
			&i.TariffID,
			&i.PackageID,
			&i.TariffName,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Error,
			&i.PayUrl,
			&i.CreatedAt,
			&i.PaidAt,
			&i.AppliedAt,
			&i.RefundedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTariffsOnSale = `-- name: ListTariffsOnSale :many
SELECT id, name, traffic_limit, duration_days, device_limit, reset_strategy, price_label, sort, archived, created_at, billing_day, price_stars, price_rub, on_sale FROM tariffs WHERE archived = 0 AND on_sale = 1 ORDER BY sort, id
`

func (q *Queries) ListTariffsOnSale(ctx context.Context) ([]Tariff, error) {
	rows, err := q.db.QueryContext(ctx, listTariffsOnSale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tariff{}
	for rows.Next() {
		var i Tariff
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TrafficLimit,
			&i.DurationDays,
			&i.DeviceLimit,
			&i.ResetStrategy,
			&i.PriceLabel,
			&i.Sort,
			&i.Archived,
			&i.CreatedAt,
			&i.BillingDay,
			&i.PriceStars,
			&i.PriceRub,
			&i.OnSale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentApplied = `-- name: MarkPaymentApplied :execrows
UPDATE payments SET status = 'applied', user_id = ?, applied_at = ?, error = ''
WHERE id = ? AND status = 'paid'
`

type MarkPaymentAppliedParams struct {
	UserID    sql.NullInt64
	AppliedAt sql.NullInt64
	ID        int64
}

func (q *Queries) MarkPaymentApplied(ctx context.Context, arg MarkPaymentAppliedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPaymentApplied, arg.UserID, arg.AppliedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markPaymentPaid = `-- name: MarkPaymentPaid :execrows
UPDATE payments SET status = 'paid', external_id = ?, paid_at = ?
WHERE id = ? AND status IN ('pending', 'expired')
`

type MarkPaymentPaidParams struct {
	ExternalID sql.NullString
	PaidAt     sql.NullInt64
	ID         int64
}

func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPaymentPaid, arg.ExternalID, arg.PaidAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markPaymentRefunded = `-- name: MarkPaymentRefunded :execrows
UPDATE payments SET status = 'refunded', refunded_at = ? WHERE id = ? AND status = 'applied'
`

type MarkPaymentRefundedParams struct {
	RefundedAt sql.NullInt64
	ID         int64
}

func (q *Queries) MarkPaymentRefunded(ctx context.Context, arg MarkPaymentRefundedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPaymentRefunded, arg.RefundedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const paymentTotals = `-- name: PaymentTotals :many
SELECT currency, count(*) AS n, CAST(IFNULL(sum(amount), 0) AS INTEGER) AS total
FROM payments WHERE status = 'applied' AND applied_at >= ? GROUP BY currency
`

type PaymentTotalsRow struct {
	Currency string
	N        int64
	Total    int64
}

func (q *Queries) PaymentTotals(ctx context.Context, appliedAt sql.NullInt64) ([]PaymentTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, paymentTotals, appliedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentTotalsRow{}
	for rows.Next() {
		var i PaymentTotalsRow
		if err := rows.Scan(&i.Currency, &i.N, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentError = `-- name: SetPaymentError :exec
UPDATE payments SET error = ? WHERE id = ?
`

type SetPaymentErrorParams struct {
	Error string
	ID    int64
}

func (q *Queries) SetPaymentError(ctx context.Context, arg SetPaymentErrorParams) error {
	_, err := q.db.ExecContext(ctx, setPaymentError, arg.Error, arg.ID)
	return err
}

const setPaymentInvoice = `-- name: SetPaymentInvoice :exec
UPDATE payments SET external_id = ?, pay_url = ? WHERE id = ?
`

type SetPaymentInvoiceParams struct {
	ExternalID sql.NullString
	PayUrl     string
	ID         int64
}

func (q *Queries) SetPaymentInvoice(ctx context.Context, arg SetPaymentInvoiceParams) error {
	_, err := q.db.ExecContext(ctx, setPaymentInvoice, arg.ExternalID, arg.PayUrl, arg.ID)
	return err
}

const setPaymentStatus = `-- name: SetPaymentStatus :execrows
UPDATE payments SET status = ?1 WHERE id = ?2 AND status = ?3
`

type SetPaymentStatusParams struct {
	NewStatus string
	ID        int64
	OldStatus string
}

func (q *Queries) SetPaymentStatus(ctx context.Context, arg SetPaymentStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPaymentStatus, arg.NewStatus, arg.ID, arg.OldStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
