// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promocodes.sql

package db

import (
	"context"
	"database/sql"
)

const claimLatePromoRefund = `-- name: ClaimLatePromoRefund :execrows
UPDATE promo_redemptions SET refund_started_at=? WHERE id=?
  AND (status='released' OR (status='reserved' AND expires_at IS NOT NULL AND expires_at<=?))
  AND (refund_started_at IS NULL OR refund_started_at<=?)
`

type ClaimLatePromoRefundParams struct {
	RefundStartedAt   sql.NullInt64
	ID                int64
	ExpiresAt         sql.NullInt64
	RefundStartedAt_2 sql.NullInt64
}

func (q *Queries) ClaimLatePromoRefund(ctx context.Context, arg ClaimLatePromoRefundParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimLatePromoRefund,
		arg.RefundStartedAt,
		arg.ID,
		arg.ExpiresAt,
		arg.RefundStartedAt_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearDisabledPromoPools = `-- name: ClearDisabledPromoPools :exec
UPDATE promo_codes SET pool_id=NULL WHERE pool_id=? AND (enabled=0 OR deleted=1)
`

func (q *Queries) ClearDisabledPromoPools(ctx context.Context, poolID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, clearDisabledPromoPools, poolID)
	return err
}

const countActivePromoCodes = `-- name: CountActivePromoCodes :one
SELECT COUNT(*) FROM promo_codes WHERE deleted=0 AND enabled=1
  AND (starts_at IS NULL OR starts_at<=?) AND (ends_at IS NULL OR ends_at>?)
  AND (max_uses IS NULL OR used_count<max_uses)
`

type CountActivePromoCodesParams struct {
	StartsAt sql.NullInt64
	EndsAt   sql.NullInt64
}

func (q *Queries) CountActivePromoCodes(ctx context.Context, arg CountActivePromoCodesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePromoCodes, arg.StartsAt, arg.EndsAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnabledPromoCodesForPool = `-- name: CountEnabledPromoCodesForPool :one
SELECT COUNT(*) FROM promo_codes WHERE pool_id=? AND enabled=1 AND deleted=0
`

func (q *Queries) CountEnabledPromoCodesForPool(ctx context.Context, poolID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnabledPromoCodesForPool, poolID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromoCodes = `-- name: CountPromoCodes :one
SELECT COUNT(*) FROM promo_codes WHERE deleted = 0
`

func (q *Queries) CountPromoCodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPromoCodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromoRedemptions = `-- name: CountPromoRedemptions :one
SELECT COUNT(*) FROM promo_redemptions
`

func (q *Queries) CountPromoRedemptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPromoRedemptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromoUser = `-- name: CountPromoUser :one
SELECT COUNT(*) FROM promo_redemptions WHERE promo_id=? AND (tg_id=? OR user_id=?) AND status IN ('reserved','applied')
`

type CountPromoUserParams struct {
	PromoID int64
	TgID    int64
	UserID  sql.NullInt64
}

func (q *Queries) CountPromoUser(ctx context.Context, arg CountPromoUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPromoUser, arg.PromoID, arg.TgID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserPaidPayments = `-- name: CountUserPaidPayments :one
SELECT COUNT(*) FROM payments WHERE tg_id=? AND status IN ('paid','applied')
`

func (q *Queries) CountUserPaidPayments(ctx context.Context, tgID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserPaidPayments, tgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPromoCode = `-- name: CreatePromoCode :one
INSERT INTO promo_codes
(code,name,description,type,value,currency,starts_at,ends_at,max_uses,per_user_limit,discount_ttl,min_order,max_discount,tariff_ids,pool_id,first_purchase_only,new_users_only,enabled,deleted,created_at,created_by)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?) RETURNING id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by
`

type CreatePromoCodeParams struct {
	Code              string
	Name              string
	Description       string
	Type              string
	Value             int64
	Currency          string
	StartsAt          sql.NullInt64
	EndsAt            sql.NullInt64
	MaxUses           sql.NullInt64
	PerUserLimit      int64
	DiscountTtl       int64
	MinOrder          int64
	MaxDiscount       int64
	TariffIds         string
	PoolID            sql.NullInt64
	FirstPurchaseOnly int64
	NewUsersOnly      int64
	Enabled           int64
	CreatedAt         int64
	CreatedBy         sql.NullInt64
}

func (q *Queries) CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, createPromoCode,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Value,
		arg.Currency,
		arg.StartsAt,
		arg.EndsAt,
		arg.MaxUses,
		arg.PerUserLimit,
		arg.DiscountTtl,
		arg.MinOrder,
		arg.MaxDiscount,
		arg.TariffIds,
		arg.PoolID,
		arg.FirstPurchaseOnly,
		arg.NewUsersOnly,
		arg.Enabled,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.PerUserLimit,
		&i.DiscountTtl,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.TariffIds,
		&i.PoolID,
		&i.FirstPurchaseOnly,
		&i.NewUsersOnly,
		&i.Enabled,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createPromoRedemption = `-- name: CreatePromoRedemption :one
INSERT INTO promo_redemptions
(promo_id,user_id,tg_id,payment_id,status,redeemed_at,expires_at,days,bytes,discount_amount,original_amount,final_amount,currency,note)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id, promo_id, user_id, tg_id, payment_id, status, refund_started_at, redeemed_at, expires_at, days, bytes, discount_amount, original_amount, final_amount, currency, note
`

type CreatePromoRedemptionParams struct {
	PromoID        int64
	UserID         sql.NullInt64
	TgID           int64
	PaymentID      sql.NullInt64
	Status         string
	RedeemedAt     int64
	ExpiresAt      sql.NullInt64
	Days           int64
	Bytes          int64
	DiscountAmount int64
	OriginalAmount int64
	FinalAmount    int64
	Currency       string
	Note           string
}

func (q *Queries) CreatePromoRedemption(ctx context.Context, arg CreatePromoRedemptionParams) (PromoRedemption, error) {
	row := q.db.QueryRowContext(ctx, createPromoRedemption,
		arg.PromoID,
		arg.UserID,
		arg.TgID,
		arg.PaymentID,
		arg.Status,
		arg.RedeemedAt,
		arg.ExpiresAt,
		arg.Days,
		arg.Bytes,
		arg.DiscountAmount,
		arg.OriginalAmount,
		arg.FinalAmount,
		arg.Currency,
		arg.Note,
	)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.PromoID,
		&i.UserID,
		&i.TgID,
		&i.PaymentID,
		&i.Status,
		&i.RefundStartedAt,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.Days,
		&i.Bytes,
		&i.DiscountAmount,
		&i.OriginalAmount,
		&i.FinalAmount,
		&i.Currency,
		&i.Note,
	)
	return i, err
}

const decrementPromoUse = `-- name: DecrementPromoUse :execrows
UPDATE promo_codes SET used_count=CASE WHEN used_count>0 THEN used_count-1 ELSE 0 END WHERE id=?
`

func (q *Queries) DecrementPromoUse(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, decrementPromoUse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePromoCode = `-- name: DeletePromoCode :execrows
UPDATE promo_codes SET deleted=1, enabled=0, pool_id=NULL WHERE id=? AND deleted=0
`

func (q *Queries) DeletePromoCode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePromoCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPromoCode = `-- name: GetPromoCode :one
SELECT id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by FROM promo_codes WHERE id = ?
`

func (q *Queries) GetPromoCode(ctx context.Context, id int64) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, getPromoCode, id)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.PerUserLimit,
		&i.DiscountTtl,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.TariffIds,
		&i.PoolID,
		&i.FirstPurchaseOnly,
		&i.NewUsersOnly,
		&i.Enabled,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPromoCodeByCode = `-- name: GetPromoCodeByCode :one
SELECT id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by FROM promo_codes WHERE code = ? AND deleted=0
`

func (q *Queries) GetPromoCodeByCode(ctx context.Context, code string) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, getPromoCodeByCode, code)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.PerUserLimit,
		&i.DiscountTtl,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.TariffIds,
		&i.PoolID,
		&i.FirstPurchaseOnly,
		&i.NewUsersOnly,
		&i.Enabled,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getPromoRedemption = `-- name: GetPromoRedemption :one
SELECT id, promo_id, user_id, tg_id, payment_id, status, refund_started_at, redeemed_at, expires_at, days, bytes, discount_amount, original_amount, final_amount, currency, note FROM promo_redemptions WHERE id=?
`

func (q *Queries) GetPromoRedemption(ctx context.Context, id int64) (PromoRedemption, error) {
	row := q.db.QueryRowContext(ctx, getPromoRedemption, id)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.PromoID,
		&i.UserID,
		&i.TgID,
		&i.PaymentID,
		&i.Status,
		&i.RefundStartedAt,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.Days,
		&i.Bytes,
		&i.DiscountAmount,
		&i.OriginalAmount,
		&i.FinalAmount,
		&i.Currency,
		&i.Note,
	)
	return i, err
}

const getPromoRedemptionByPayment = `-- name: GetPromoRedemptionByPayment :one
SELECT id, promo_id, user_id, tg_id, payment_id, status, refund_started_at, redeemed_at, expires_at, days, bytes, discount_amount, original_amount, final_amount, currency, note FROM promo_redemptions WHERE payment_id=?
`

func (q *Queries) GetPromoRedemptionByPayment(ctx context.Context, paymentID sql.NullInt64) (PromoRedemption, error) {
	row := q.db.QueryRowContext(ctx, getPromoRedemptionByPayment, paymentID)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.PromoID,
		&i.UserID,
		&i.TgID,
		&i.PaymentID,
		&i.Status,
		&i.RefundStartedAt,
		&i.RedeemedAt,
		&i.ExpiresAt,
		&i.Days,
		&i.Bytes,
		&i.DiscountAmount,
		&i.OriginalAmount,
		&i.FinalAmount,
		&i.Currency,
		&i.Note,
	)
	return i, err
}

const incrementPromoUse = `-- name: IncrementPromoUse :execrows
UPDATE promo_codes SET used_count=used_count+1 WHERE id=? AND (max_uses IS NULL OR used_count < max_uses) AND deleted=0 AND enabled=1
`

func (q *Queries) IncrementPromoUse(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementPromoUse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listExpiredPromoPayments = `-- name: ListExpiredPromoPayments :many
SELECT DISTINCT p.id FROM payments p JOIN promo_redemptions r ON r.payment_id=p.id WHERE p.status='expired' AND p.created_at < ? AND r.status='reserved'
`

func (q *Queries) ListExpiredPromoPayments(ctx context.Context, createdAt int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredPromoPayments, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoCodes = `-- name: ListPromoCodes :many
SELECT id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by FROM promo_codes WHERE deleted = 0 ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListPromoCodesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPromoCodes(ctx context.Context, arg ListPromoCodesParams) ([]PromoCode, error) {
	rows, err := q.db.QueryContext(ctx, listPromoCodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromoCode{}
	for rows.Next() {
		var i PromoCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Value,
			&i.Currency,
			&i.StartsAt,
			&i.EndsAt,
			&i.MaxUses,
			&i.UsedCount,
			&i.PerUserLimit,
			&i.DiscountTtl,
			&i.MinOrder,
			&i.MaxDiscount,
			&i.TariffIds,
			&i.PoolID,
			&i.FirstPurchaseOnly,
			&i.NewUsersOnly,
			&i.Enabled,
			&i.Deleted,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoRedemptions = `-- name: ListPromoRedemptions :many
SELECT id, promo_id, user_id, tg_id, payment_id, status, refund_started_at, redeemed_at, expires_at, days, bytes, discount_amount, original_amount, final_amount, currency, note FROM promo_redemptions ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListPromoRedemptionsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPromoRedemptions(ctx context.Context, arg ListPromoRedemptionsParams) ([]PromoRedemption, error) {
	rows, err := q.db.QueryContext(ctx, listPromoRedemptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromoRedemption{}
	for rows.Next() {
		var i PromoRedemption
		if err := rows.Scan(
			&i.ID,
			&i.PromoID,
			&i.UserID,
			&i.TgID,
			&i.PaymentID,
			&i.Status,
			&i.RefundStartedAt,
			&i.RedeemedAt,
			&i.ExpiresAt,
			&i.Days,
			&i.Bytes,
			&i.DiscountAmount,
			&i.OriginalAmount,
			&i.FinalAmount,
			&i.Currency,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoRedemptionsByTg = `-- name: ListPromoRedemptionsByTg :many
SELECT id, promo_id, user_id, tg_id, payment_id, status, refund_started_at, redeemed_at, expires_at, days, bytes, discount_amount, original_amount, final_amount, currency, note FROM promo_redemptions WHERE tg_id=? AND status='applied' ORDER BY id DESC LIMIT ?
`

type ListPromoRedemptionsByTgParams struct {
	TgID  int64
	Limit int64
}

func (q *Queries) ListPromoRedemptionsByTg(ctx context.Context, arg ListPromoRedemptionsByTgParams) ([]PromoRedemption, error) {
	rows, err := q.db.QueryContext(ctx, listPromoRedemptionsByTg, arg.TgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromoRedemption{}
	for rows.Next() {
		var i PromoRedemption
		if err := rows.Scan(
			&i.ID,
			&i.PromoID,
			&i.UserID,
			&i.TgID,
			&i.PaymentID,
			&i.Status,
			&i.RefundStartedAt,
			&i.RedeemedAt,
			&i.ExpiresAt,
			&i.Days,
			&i.Bytes,
			&i.DiscountAmount,
			&i.OriginalAmount,
			&i.FinalAmount,
			&i.Currency,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPromoApplied = `-- name: MarkPromoApplied :execrows
UPDATE promo_redemptions SET status='applied', user_id=COALESCE(?,user_id) WHERE id=? AND status='reserved'
`

type MarkPromoAppliedParams struct {
	UserID sql.NullInt64
	ID     int64
}

func (q *Queries) MarkPromoApplied(ctx context.Context, arg MarkPromoAppliedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPromoApplied, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const promoStats = `-- name: PromoStats :one
SELECT COUNT(CASE WHEN status='applied' THEN 1 END), COALESCE(SUM(CASE WHEN status='applied' THEN days ELSE 0 END),0), COALESCE(SUM(CASE WHEN status='applied' THEN bytes ELSE 0 END),0), COALESCE(SUM(CASE WHEN status='applied' THEN discount_amount ELSE 0 END),0), COALESCE(SUM(CASE WHEN status='applied' AND payment_id IS NOT NULL THEN 1 ELSE 0 END),0) FROM promo_redemptions
`

type PromoStatsRow struct {
	Count      int64
	Coalesce   interface{}
	Coalesce_2 interface{}
	Coalesce_3 interface{}
	Coalesce_4 interface{}
}

func (q *Queries) PromoStats(ctx context.Context) (PromoStatsRow, error) {
	row := q.db.QueryRowContext(ctx, promoStats)
	var i PromoStatsRow
	err := row.Scan(
		&i.Count,
		&i.Coalesce,
		&i.Coalesce_2,
		&i.Coalesce_3,
		&i.Coalesce_4,
	)
	return i, err
}

const releasePromoByPayment = `-- name: ReleasePromoByPayment :execrows
UPDATE promo_redemptions SET status='released' WHERE payment_id=? AND status='reserved'
`

func (q *Queries) ReleasePromoByPayment(ctx context.Context, paymentID sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, releasePromoByPayment, paymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releasePromoRedemption = `-- name: ReleasePromoRedemption :execrows
UPDATE promo_redemptions SET status='released' WHERE id=? AND status='reserved'
`

func (q *Queries) ReleasePromoRedemption(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, releasePromoRedemption, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const releasePromoRedemptionForClosedPayment = `-- name: ReleasePromoRedemptionForClosedPayment :execrows
UPDATE promo_redemptions SET status='released'
WHERE promo_redemptions.id=? AND promo_redemptions.status='reserved' AND EXISTS (
  SELECT 1 FROM payments p WHERE p.id=promo_redemptions.payment_id AND p.status IN ('failed','expired','refunded')
)
`

func (q *Queries) ReleasePromoRedemptionForClosedPayment(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, releasePromoRedemptionForClosedPayment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPromoEnabled = `-- name: SetPromoEnabled :execrows
UPDATE promo_codes SET enabled=? WHERE id=? AND deleted=0
`

type SetPromoEnabledParams struct {
	Enabled int64
	ID      int64
}

func (q *Queries) SetPromoEnabled(ctx context.Context, arg SetPromoEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPromoEnabled, arg.Enabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePromoCode = `-- name: UpdatePromoCode :one
UPDATE promo_codes SET
code=?,name=?,description=?,type=?,value=?,currency=?,starts_at=?,ends_at=?,max_uses=?,per_user_limit=?,discount_ttl=?,min_order=?,max_discount=?,tariff_ids=?,pool_id=?,first_purchase_only=?,new_users_only=?,enabled=? WHERE id=? AND deleted=0 RETURNING id, code, name, description, type, value, currency, starts_at, ends_at, max_uses, used_count, per_user_limit, discount_ttl, min_order, max_discount, tariff_ids, pool_id, first_purchase_only, new_users_only, enabled, deleted, created_at, created_by
`

type UpdatePromoCodeParams struct {
	Code              string
	Name              string
	Description       string
	Type              string
	Value             int64
	Currency          string
	StartsAt          sql.NullInt64
	EndsAt            sql.NullInt64
	MaxUses           sql.NullInt64
	PerUserLimit      int64
	DiscountTtl       int64
	MinOrder          int64
	MaxDiscount       int64
	TariffIds         string
	PoolID            sql.NullInt64
	FirstPurchaseOnly int64
	NewUsersOnly      int64
	Enabled           int64
	ID                int64
}

func (q *Queries) UpdatePromoCode(ctx context.Context, arg UpdatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRowContext(ctx, updatePromoCode,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Value,
		arg.Currency,
		arg.StartsAt,
		arg.EndsAt,
		arg.MaxUses,
		arg.PerUserLimit,
		arg.DiscountTtl,
		arg.MinOrder,
		arg.MaxDiscount,
		arg.TariffIds,
		arg.PoolID,
		arg.FirstPurchaseOnly,
		arg.NewUsersOnly,
		arg.Enabled,
		arg.ID,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Value,
		&i.Currency,
		&i.StartsAt,
		&i.EndsAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.PerUserLimit,
		&i.DiscountTtl,
		&i.MinOrder,
		&i.MaxDiscount,
		&i.TariffIds,
		&i.PoolID,
		&i.FirstPurchaseOnly,
		&i.NewUsersOnly,
		&i.Enabled,
		&i.Deleted,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
