-- +goose Up
CREATE TABLE IF NOT EXISTS promo_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL CHECK (type IN ('days','traffic','percent','fixed')),
  value BIGINT NOT NULL CHECK (value > 0),
  currency TEXT NOT NULL DEFAULT '' CHECK (currency IN ('','XTR','RUB')),
  starts_at BIGINT,
  ends_at BIGINT,
  max_uses BIGINT CHECK (max_uses IS NULL OR max_uses > 0),
  used_count BIGINT NOT NULL DEFAULT 0 CHECK (used_count >= 0),
  per_user_limit BIGINT NOT NULL DEFAULT 1 CHECK (per_user_limit > 0),
  discount_ttl BIGINT NOT NULL DEFAULT 0 CHECK (discount_ttl >= 0),
  min_order BIGINT NOT NULL DEFAULT 0 CHECK (min_order >= 0),
  max_discount BIGINT NOT NULL DEFAULT 0 CHECK (max_discount >= 0),
  tariff_ids TEXT NOT NULL DEFAULT '[]',
  pool_id BIGINT REFERENCES traffic_pools(id) ON DELETE RESTRICT,
  first_purchase_only BIGINT NOT NULL DEFAULT 0 CHECK (first_purchase_only IN (0,1)),
  new_users_only BIGINT NOT NULL DEFAULT 0 CHECK (new_users_only IN (0,1)),
  enabled BIGINT NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
  deleted BIGINT NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
  created_at BIGINT NOT NULL,
  created_by BIGINT REFERENCES admins(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS promo_codes_active ON promo_codes(enabled, deleted, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS promo_codes_type ON promo_codes(type);
CREATE UNIQUE INDEX IF NOT EXISTS promo_codes_code_active ON promo_codes(code) WHERE deleted=0;

CREATE TABLE IF NOT EXISTS promo_redemptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promo_id BIGINT NOT NULL REFERENCES promo_codes(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  tg_id BIGINT NOT NULL,
  payment_id BIGINT UNIQUE REFERENCES payments(id) ON DELETE SET NULL,
  status TEXT NOT NULL CHECK (status IN ('reserved','applied','released')),
  refund_started_at BIGINT,
  redeemed_at BIGINT NOT NULL,
  expires_at BIGINT,
  days BIGINT NOT NULL DEFAULT 0,
  bytes BIGINT NOT NULL DEFAULT 0,
  discount_amount BIGINT NOT NULL DEFAULT 0,
  original_amount BIGINT NOT NULL DEFAULT 0,
  final_amount BIGINT NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT '',
  note TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS promo_redemptions_promo ON promo_redemptions(promo_id, redeemed_at);
CREATE INDEX IF NOT EXISTS promo_redemptions_user ON promo_redemptions(user_id, redeemed_at);
CREATE INDEX IF NOT EXISTS promo_redemptions_payment ON promo_redemptions(payment_id);

-- +goose Down
DROP TABLE promo_redemptions;
DROP TABLE promo_codes;
